spring.datasource.url=jdbc:postgresql://localhost:5434/db_controle_estoque
spring.datasource.username=estoqueuser
spring.datasource.password=estoquepassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=tyhkFWQpTvR1zs/wP/mtphAQ6q9RxAcYkXjyYRPUfi4=
jwt.expiration=3600000

spring.flyway.enabled=true
spring.flyway.schemas=estoque

admin.email=teste@admin.com
admin.password=s3nh@@dm1n)!crKk

logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG
logging.level.br.com.controleestoqueapi=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.flywaydb=DEBUG