-- Apaga as tabelas (se existirem)
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

-- Cria as tabelas
CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL UNIQUE,
    password     VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    address      VARCHAR(255)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

INSERT INTO users (name, email, password, phone_number, address)
VALUES ('Usuário Teste', 'teste@admin.com', '$2a$10$OY0BncQQNK4pZruy1hz0/u8xwt.Nbr6xqzDycwGePywUv.4XBo9nC', '123456789',
        'Rua Teste');

INSERT INTO user_roles (user_id, role)
VALUES ((SELECT id FROM users WHERE email = 'teste@admin.com'), 'ADMIN');